### ISSUE TITLE
When I send new api request after long time inactives. I have the error.

### ISSUE THREAD

**Issue by andrewobukhov** [ringcentral/ringcentral-java#1]
When I send new api request after long time inactives(about 10 hours). I have the error: 
{
  "errorCode" : "AGW-402",
  "message" : "Invalid Authorization header",
  "errors" : [ {
    "errorCode" : "AGW-402",
    "message" : "Invalid Authorization header"
  } ]
}

Then I have to call method authorize again:
 restClient.authorize(username, extension, password);

Despite property "autorefresh" is true.

Expected behavior:  
I don't need authorize again after long time inactives.

**Comment by tylerlong** [comment]
Can you reproduce this issue constantly? I did some test but found it hard to reproduce(10 hours to wait). It might because the server side revoke the token (It's unlikely but still possible).

The behavior of autoRefresh is https://github.com/ringcentral/ringcentral-java/blob/master/src/main/java/com/ringcentral/RestClient.java#L40-L47

It auto refreshes 2 minutes before the token expires. No more magic here. So a quick workaround is you setup a timer to call the refresh method 1 hour or so.
