### ISSUE TITLE
Trying to migrate to 3.0.0 nothing for CallerInfoTo.faxErrorCode ?

### ISSUE THREAD

**Issue by mikrethor** [ringcentral/ringcentral-java#40]
I am trying to migrate from 2 to 3 and I have a hard time finding the corresponding type in 3.0.0 for CallerInfoTo.faxErrorCode.

I found looking in the code that CallerInfoTo has been renamed to FaxResponseTo but I don't find anything related to the faxErrorCode.

Is there any doc migration or openrewrite recipe?

**Comment by tylerlong** [comment]
Could you please post some code snippets? I don't understand the "faxErrorCode" part.

According to latest spec, there is no "faxErrorCode":

```
    FaxResponseTo:
      type: "object"
      properties:
        phoneNumber:
          type: "string"
          description: "Phone number in E.164 (with '+' sign) format"
          example: "+18661234567"
        name:
          type: "string"
          description: "Name of a fax recipient listed on a fax cover page"
        messageStatus:
          type: "string"
          $ref: "#/components/schemas/MessageStatusEnum"
```

99% of the SDK is generated based on spec. If something disappeared, it means it has been removed from spec.
Please post more details so that we could analyze it case by case.
